# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d8422d5d4cd5e7f4a250b30a5fd82b80cb31c002942083d7d24ab23bbc8331882d350bc8ee269b409142b83ec0cd7fcea24606862503c57c3efb57178a26546

test:
  secret_key_base: c6cd4d5b6f54dd358df41d2211d4d9a88cfafda0d7ab1af18e8ea13c2e8b60db91bad2200274d3df0d3e2c6ccc235e837fc18d965d47bb5fd07f23d960c5c753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
